// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCTVS6P5-u4V_CB2OxPaIwvubdKYJk8bk',
    appId: '1:551580028728:web:b5f5cbc5f53d201bb23bcd',
    messagingSenderId: '551580028728',
    projectId: 'lifeos-493607',
    authDomain: 'lifeos-493607.firebaseapp.com',
    storageBucket: 'lifeos-493607.firebasestorage.app',
    measurementId: 'G-NJP1MEWFFX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGPeBuOCzroq0GdY5yDmsie7Q8_dMDXVw',
    appId: '1:551580028728:ios:8fb1ba175da2401ab23bcd',
    messagingSenderId: '551580028728',
    projectId: 'lifeos-493607',
    storageBucket: 'lifeos-493607.firebasestorage.app',
    iosBundleId: 'com.example.lifeos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCTVS6P5-u4V_CB2OxPaIwvubdKYJk8bk',
    appId: '1:551580028728:web:5219f89fb8afff2db23bcd',
    messagingSenderId: '551580028728',
    projectId: 'lifeos-493607',
    authDomain: 'lifeos-493607.firebaseapp.com',
    storageBucket: 'lifeos-493607.firebasestorage.app',
    measurementId: 'G-DGJSN4J3CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIT6HLOAO4wqD7gRF5uZ4KdQlw8ecrfN8',
    appId: '1:551580028728:android:1c60e601a422eb79b23bcd',
    messagingSenderId: '551580028728',
    projectId: 'lifeos-493607',
    storageBucket: 'lifeos-493607.firebasestorage.app',
  );

}